# Generated by Django 5.1.15 on 2026-08-11 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
        ('reservations', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actual_check_in', models.DateTimeField()),
                ('actual_check_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stays', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='guests.guest')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='reservations.reservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='rooms.room')),
            ],
            options={
                'ordering': ['-actual_check_in'],
                'indexes': [models.Index(fields=['reservation'], name='stay_reservation_idx'), models.Index(fields=['guest'], name='stay_guest_idx'), models.Index(fields=['room'], name='stay_room_idx'), models.Index(fields=['status'], name='stay_status_idx')],
            },
        ),
    ]
