# Generated by Django 5.1.15 on 2026-08-11 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation_number', models.CharField(max_length=40, unique=True)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('adults', models.PositiveSmallIntegerField(default=1)),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked in'), ('CHECKED_OUT', 'Checked out'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No show')], default='PENDING', max_length=20)),
                ('source', models.CharField(choices=[('WALK_IN', 'Walk in'), ('PHONE', 'Phone'), ('EMAIL', 'Email'), ('WEBSITE', 'Website'), ('AGENT', 'Agent'), ('OTHER', 'Other')], default='WALK_IN', max_length=20)),
                ('special_requests', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(help_text='Primary guest for MVP compatibility; additional guests use ReservationGuest.', on_delete=django.db.models.deletion.PROTECT, related_name='primary_reservations', to='guests.guest')),
                ('room', models.ForeignKey(help_text='Room references are protected to preserve reservation history.', on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='rooms.room')),
            ],
            options={
                'ordering': ['-check_in_date', 'reservation_number'],
            },
        ),
        migrations.CreateModel(
            name='ReservationGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_links', to='guests.guest')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_guests', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='guests',
            field=models.ManyToManyField(related_name='reservations', through='reservations.ReservationGuest', to='guests.guest'),
        ),
        migrations.AddIndex(
            model_name='reservationguest',
            index=models.Index(fields=['reservation'], name='res_guest_reservation_idx'),
        ),
        migrations.AddIndex(
            model_name='reservationguest',
            index=models.Index(fields=['guest'], name='res_guest_guest_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservationguest',
            constraint=models.UniqueConstraint(fields=('reservation', 'guest'), name='unique_reservation_guest'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['guest'], name='reservation_guest_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['room'], name='reservation_room_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status'], name='reservation_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['check_in_date'], name='reservation_checkin_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['check_out_date'], name='reservation_checkout_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['room', 'check_in_date', 'check_out_date'], name='reservation_room_dates_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('reservation_number',), name='unique_reservation_number'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('check_out_date__gt', models.F('check_in_date'))), name='reservation_checkout_after_checkin'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('adults__gt', 0)), name='reservation_adults_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('children__gte', 0)), name='reservation_children_gte_0'),
        ),
    ]
