# Generated by Django 5.1.15 on 2026-08-11 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_room_type_name'), models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='room_type_capacity_gt_0'), models.CheckConstraint(condition=models.Q(('base_price__gte', 0)), name='room_type_base_price_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_number', models.CharField(max_length=20, unique=True)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved'), ('DIRTY', 'Dirty'), ('MAINTENANCE', 'Maintenance'), ('OUT_OF_SERVICE', 'Out of service')], default='AVAILABLE', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('room_type', models.ForeignKey(help_text='Room types are protected because rooms and historical stays may depend on them.', on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['room_number'],
                'indexes': [models.Index(fields=['room_type'], name='room_room_type_idx'), models.Index(fields=['status'], name='room_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('room_number',), name='unique_room_number')],
            },
        ),
    ]
