# Generated by Django 5.1.15 on 2026-08-11 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_reference', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('POS', 'POS'), ('BANK_TRANSFER', 'Bank transfer'), ('CARD', 'Card'), ('ONLINE', 'Online'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.invoice')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_at', '-created_at'],
                'indexes': [models.Index(fields=['invoice'], name='payment_invoice_idx'), models.Index(fields=['transaction_reference'], name='payment_transaction_ref_idx'), models.Index(fields=['status'], name='payment_status_idx'), models.Index(fields=['paid_at'], name='payment_paid_at_idx')],
                'constraints': [models.UniqueConstraint(fields=('payment_reference',), name='unique_payment_reference'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_gt_0')],
            },
        ),
    ]
