# Generated by Django 5.1.15 on 2026-08-14 23:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_notes_invoice_stay_alter_invoice_discount_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_transaction_ref_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_paid_at_idx',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paid_at',
            new_name='payment_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_reference',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Payment amount in NGN', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('POS', 'POS'), ('BANK_TRANSFER', 'Bank transfer'), ('OTHER', 'Other')], default='CASH', max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_reference'], name='payment_reference_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='payment_date_idx'),
        ),
    ]
