-- MTA Hotel HMS PostgreSQL schema
-- Source of truth for Django is still backend/apps/*/migrations/.
-- This file is a readable SQL reference for the project-specific tables.
-- Django also creates built-in tables for admin, auth, contenttypes, and sessions.

CREATE TABLE accounts_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    name VARCHAR(50) NOT NULL UNIQUE,
    description TEXT NOT NULL,
    CONSTRAINT unique_role_name UNIQUE (name)
);

CREATE INDEX role_name_idx ON accounts_role (name);

CREATE TABLE accounts_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password VARCHAR(128) NOT NULL,
    last_login TIMESTAMPTZ NULL,
    is_superuser BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE,
    first_name VARCHAR(150) NOT NULL,
    last_name VARCHAR(150) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    is_active BOOLEAN NOT NULL,
    is_staff BOOLEAN NOT NULL,
    date_joined TIMESTAMPTZ NOT NULL,
    role_id BIGINT NULL REFERENCES accounts_role (id) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX user_email_idx ON accounts_user (email);
CREATE INDEX user_role_idx ON accounts_user (role_id);

CREATE TABLE accounts_user_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES accounts_user (id) DEFERRABLE INITIALLY DEFERRED,
    group_id INTEGER NOT NULL REFERENCES auth_group (id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT accounts_user_groups_user_id_group_id_unique UNIQUE (user_id, group_id)
);

CREATE INDEX accounts_user_groups_user_id_idx ON accounts_user_groups (user_id);
CREATE INDEX accounts_user_groups_group_id_idx ON accounts_user_groups (group_id);

CREATE TABLE accounts_user_user_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES accounts_user (id) DEFERRABLE INITIALLY DEFERRED,
    permission_id INTEGER NOT NULL REFERENCES auth_permission (id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT accounts_user_user_permissions_user_id_permission_id_unique UNIQUE (user_id, permission_id)
);

CREATE INDEX accounts_user_user_permissions_user_id_idx ON accounts_user_user_permissions (user_id);
CREATE INDEX accounts_user_user_permissions_permission_id_idx ON accounts_user_user_permissions (permission_id);

CREATE TABLE guests_guest (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    guest_code VARCHAR(30) NOT NULL UNIQUE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    email VARCHAR(254) NOT NULL,
    address TEXT NOT NULL,
    id_type VARCHAR(50) NOT NULL,
    id_number VARCHAR(80) NOT NULL,
    nationality VARCHAR(80) NOT NULL,
    date_of_birth DATE NULL,
    emergency_contact_name VARCHAR(150) NOT NULL,
    emergency_contact_phone VARCHAR(30) NOT NULL,
    notes TEXT NOT NULL,
    CONSTRAINT unique_guest_code UNIQUE (guest_code)
);

CREATE INDEX guest_phone_idx ON guests_guest (phone);
CREATE INDEX guest_email_idx ON guests_guest (email);
CREATE INDEX guest_id_number_idx ON guests_guest (id_number);

CREATE TABLE rooms_roomtype (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    name VARCHAR(80) NOT NULL UNIQUE,
    description TEXT NOT NULL,
    capacity SMALLINT NOT NULL,
    base_price NUMERIC(12, 2) NOT NULL,
    CONSTRAINT unique_room_type_name UNIQUE (name),
    CONSTRAINT room_type_capacity_gt_0 CHECK (capacity > 0),
    CONSTRAINT room_type_base_price_gte_0 CHECK (base_price >= 0),
    CONSTRAINT rooms_roomtype_capacity_nonnegative CHECK (capacity >= 0)
);

CREATE TABLE rooms_room (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    room_number VARCHAR(20) NOT NULL UNIQUE,
    floor VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    description TEXT NOT NULL,
    room_type_id BIGINT NOT NULL REFERENCES rooms_roomtype (id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT unique_room_number UNIQUE (room_number)
);

CREATE INDEX room_room_type_idx ON rooms_room (room_type_id);
CREATE INDEX room_status_idx ON rooms_room (status);

CREATE TABLE reservations_reservation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    reservation_number VARCHAR(40) NOT NULL UNIQUE,
    check_in_date DATE NOT NULL,
    check_out_date DATE NOT NULL,
    adults SMALLINT NOT NULL,
    children SMALLINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    source VARCHAR(20) NOT NULL,
    special_requests TEXT NOT NULL,
    notes TEXT NOT NULL,
    created_by_id BIGINT NULL REFERENCES accounts_user (id) DEFERRABLE INITIALLY DEFERRED,
    guest_id BIGINT NOT NULL REFERENCES guests_guest (id) DEFERRABLE INITIALLY DEFERRED,
    room_id BIGINT NOT NULL REFERENCES rooms_room (id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT unique_reservation_number UNIQUE (reservation_number),
    CONSTRAINT reservation_checkout_after_checkin CHECK (check_out_date > check_in_date),
    CONSTRAINT reservation_adults_gt_0 CHECK (adults > 0),
    CONSTRAINT reservation_children_gte_0 CHECK (children >= 0),
    CONSTRAINT reservations_reservation_adults_nonnegative CHECK (adults >= 0),
    CONSTRAINT reservations_reservation_children_nonnegative CHECK (children >= 0)
);

CREATE INDEX reservation_guest_idx ON reservations_reservation (guest_id);
CREATE INDEX reservation_room_idx ON reservations_reservation (room_id);
CREATE INDEX reservation_status_idx ON reservations_reservation (status);
CREATE INDEX reservation_checkin_idx ON reservations_reservation (check_in_date);
CREATE INDEX reservation_checkout_idx ON reservations_reservation (check_out_date);
CREATE INDEX reservation_room_dates_idx ON reservations_reservation (room_id, check_in_date, check_out_date);

CREATE TABLE reservations_reservationguest (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_primary BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    guest_id BIGINT NOT NULL REFERENCES guests_guest (id) DEFERRABLE INITIALLY DEFERRED,
    reservation_id BIGINT NOT NULL REFERENCES reservations_reservation (id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT unique_reservation_guest UNIQUE (reservation_id, guest_id)
);

CREATE INDEX res_guest_reservation_idx ON reservations_reservationguest (reservation_id);
CREATE INDEX res_guest_guest_idx ON reservations_reservationguest (guest_id);

CREATE TABLE stays_stay (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    actual_check_in TIMESTAMPTZ NOT NULL,
    actual_check_out TIMESTAMPTZ NULL,
    status VARCHAR(20) NOT NULL,
    created_by_id BIGINT NULL REFERENCES accounts_user (id) DEFERRABLE INITIALLY DEFERRED,
    guest_id BIGINT NOT NULL REFERENCES guests_guest (id) DEFERRABLE INITIALLY DEFERRED,
    reservation_id BIGINT NOT NULL REFERENCES reservations_reservation (id) DEFERRABLE INITIALLY DEFERRED,
    room_id BIGINT NOT NULL REFERENCES rooms_room (id) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX stay_reservation_idx ON stays_stay (reservation_id);
CREATE INDEX stay_guest_idx ON stays_stay (guest_id);
CREATE INDEX stay_room_idx ON stays_stay (room_id);
CREATE INDEX stay_status_idx ON stays_stay (status);

CREATE TABLE billing_invoice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    invoice_number VARCHAR(40) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL,
    subtotal NUMERIC(12, 2) NOT NULL,
    discount NUMERIC(12, 2) NOT NULL,
    tax NUMERIC(12, 2) NOT NULL,
    total NUMERIC(12, 2) NOT NULL,
    amount_paid NUMERIC(12, 2) NOT NULL,
    balance NUMERIC(12, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    issued_at TIMESTAMPTZ NULL,
    due_at TIMESTAMPTZ NULL,
    created_by_id BIGINT NULL REFERENCES accounts_user (id) DEFERRABLE INITIALLY DEFERRED,
    guest_id BIGINT NOT NULL REFERENCES guests_guest (id) DEFERRABLE INITIALLY DEFERRED,
    reservation_id BIGINT NOT NULL REFERENCES reservations_reservation (id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT unique_invoice_number UNIQUE (invoice_number),
    CONSTRAINT invoice_subtotal_gte_0 CHECK (subtotal >= 0),
    CONSTRAINT invoice_discount_gte_0 CHECK (discount >= 0),
    CONSTRAINT invoice_tax_gte_0 CHECK (tax >= 0),
    CONSTRAINT invoice_total_gte_0 CHECK (total >= 0),
    CONSTRAINT invoice_amount_paid_gte_0 CHECK (amount_paid >= 0),
    CONSTRAINT invoice_balance_gte_0 CHECK (balance >= 0)
);

CREATE INDEX invoice_guest_idx ON billing_invoice (guest_id);
CREATE INDEX invoice_reservation_idx ON billing_invoice (reservation_id);
CREATE INDEX invoice_status_idx ON billing_invoice (status);
CREATE INDEX invoice_issued_at_idx ON billing_invoice (issued_at);

CREATE TABLE billing_invoiceitem (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_type VARCHAR(20) NOT NULL,
    description VARCHAR(255) NOT NULL,
    quantity NUMERIC(10, 2) NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    service_date DATE NULL,
    created_at TIMESTAMPTZ NOT NULL,
    invoice_id BIGINT NOT NULL REFERENCES billing_invoice (id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT invoice_item_quantity_gt_0 CHECK (quantity > 0),
    CONSTRAINT invoice_item_unit_price_gte_0 CHECK (unit_price >= 0),
    CONSTRAINT invoice_item_amount_gte_0 CHECK (amount >= 0)
);

CREATE INDEX invoice_item_invoice_idx ON billing_invoiceitem (invoice_id);
CREATE INDEX invoice_item_type_idx ON billing_invoiceitem (item_type);
CREATE INDEX invoice_item_service_date_idx ON billing_invoiceitem (service_date);

CREATE TABLE payments_payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    payment_reference VARCHAR(50) NOT NULL UNIQUE,
    amount NUMERIC(12, 2) NOT NULL,
    method VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    transaction_reference VARCHAR(100) NOT NULL,
    paid_at TIMESTAMPTZ NULL,
    notes TEXT NOT NULL,
    invoice_id BIGINT NOT NULL REFERENCES billing_invoice (id) DEFERRABLE INITIALLY DEFERRED,
    received_by_id BIGINT NULL REFERENCES accounts_user (id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT unique_payment_reference UNIQUE (payment_reference),
    CONSTRAINT payment_amount_gt_0 CHECK (amount > 0)
);

CREATE INDEX payment_invoice_idx ON payments_payment (invoice_id);
CREATE INDEX payment_transaction_ref_idx ON payments_payment (transaction_reference);
CREATE INDEX payment_status_idx ON payments_payment (status);
CREATE INDEX payment_paid_at_idx ON payments_payment (paid_at);

CREATE TABLE audit_auditlog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(20) NOT NULL,
    module VARCHAR(50) NOT NULL,
    object_type VARCHAR(100) NOT NULL,
    object_id VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    ip_address INET NULL,
    created_at TIMESTAMPTZ NOT NULL,
    user_id BIGINT NULL REFERENCES accounts_user (id) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX audit_user_idx ON audit_auditlog (user_id);
CREATE INDEX audit_module_idx ON audit_auditlog (module);
CREATE INDEX audit_object_type_idx ON audit_auditlog (object_type);
CREATE INDEX audit_object_id_idx ON audit_auditlog (object_id);
CREATE INDEX audit_created_at_idx ON audit_auditlog (created_at);
